"""add structured PFZ table fields (direction, bearing, distance, depth, DMS)

Revision ID: 66b1a33ee867
Revises: c22c2574b960
Create Date: 2026-08-19 15:13:46.917585

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '66b1a33ee867'
down_revision: Union[str, Sequence[str], None] = 'c22c2574b960'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfz_advisories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('landing_center', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('direction', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('bearing_deg', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('distance_km_range', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('depth_m_range', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('latitude_dms', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('longitude_dms', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfz_advisories', schema=None) as batch_op:
        batch_op.drop_column('longitude_dms')
        batch_op.drop_column('latitude_dms')
        batch_op.drop_column('depth_m_range')
        batch_op.drop_column('distance_km_range')
        batch_op.drop_column('bearing_deg')
        batch_op.drop_column('direction')
        batch_op.drop_column('landing_center')

    # ### end Alembic commands ###
