"""add source_updated_at to pfz_advisories

Revision ID: bcee1a11766c
Revises: 66b1a33ee867
Create Date: 2026-08-19 16:01:11.211083

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcee1a11766c'
down_revision: Union[str, Sequence[str], None] = '66b1a33ee867'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfz_advisories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('source_updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pfz_advisories', schema=None) as batch_op:
        batch_op.drop_column('source_updated_at')

    # ### end Alembic commands ###
