"""initial schema

Revision ID: c22c2574b960
Revises: 
Create Date: 2026-08-19 12:56:25.217211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c22c2574b960'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('harbours',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('district', sa.String(), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('pfz_advisories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('reference_point', sa.String(), nullable=True),
    sa.Column('sea_surface_temp_c', sa.Float(), nullable=True),
    sa.Column('chlorophyll_mg_m3', sa.Float(), nullable=True),
    sa.Column('valid_from', sa.DateTime(), nullable=False),
    sa.Column('valid_to', sa.DateTime(), nullable=False),
    sa.Column('source', sa.String(), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('product_categories',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['product_categories.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('phone_number', sa.String(), nullable=False),
    sa.Column('role', sa.Enum('fisherman', 'cooperative', 'vendor', 'buyer', 'admin', name='userrole'), nullable=False),
    sa.Column('kyc_status', sa.Enum('unverified', 'phone_verified', 'full_kyc', name='kycstatus'), nullable=False),
    sa.Column('aadhaar_last4', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('phone_number', 'role', name='uq_users_phone_role')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_phone_number'), ['phone_number'], unique=False)

    op.create_table('buyer_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('fssai_license_no', sa.String(), nullable=True),
    sa.Column('mpeda_registration_no', sa.String(), nullable=True),
    sa.Column('bank_account_verified', sa.Boolean(), nullable=True),
    sa.Column('sourcing_species', sa.String(), nullable=True),
    sa.Column('processing_capacity_tonnes_per_month', sa.Integer(), nullable=True),
    sa.Column('preferred_delivery_hub', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('cooperative_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('society_name', sa.String(), nullable=False),
    sa.Column('society_registration_no', sa.String(), nullable=True),
    sa.Column('officer_in_charge_name', sa.String(), nullable=True),
    sa.Column('harbour_id', sa.String(), nullable=True),
    sa.Column('active_fleet_count', sa.Integer(), nullable=True),
    sa.Column('primary_catch_varieties', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['harbour_id'], ['harbours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('price_records',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('harbour_id', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('record_date', sa.Date(), nullable=False),
    sa.Column('landing_volume_kg', sa.Float(), nullable=True),
    sa.Column('min_price_per_kg', sa.Float(), nullable=False),
    sa.Column('max_price_per_kg', sa.Float(), nullable=False),
    sa.Column('avg_price_per_kg', sa.Float(), nullable=False),
    sa.Column('entered_by_user_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['entered_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['harbour_id'], ['harbours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_records_record_date'), ['record_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_records_species'), ['species'], unique=False)

    op.create_table('vendor_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('business_name', sa.String(), nullable=False),
    sa.Column('gstin', sa.String(), nullable=True),
    sa.Column('business_license_no', sa.String(), nullable=True),
    sa.Column('shop_address', sa.String(), nullable=True),
    sa.Column('brand_authorization', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('fisherman_profiles',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('home_harbour_id', sa.String(), nullable=True),
    sa.Column('boat_type', sa.Enum('mechanized', 'motorized', 'traditional', name='boattype'), nullable=True),
    sa.Column('target_species', sa.String(), nullable=True),
    sa.Column('boat_registration_no', sa.String(), nullable=True),
    sa.Column('access_pass_no', sa.String(), nullable=True),
    sa.Column('high_sea_pass_no', sa.String(), nullable=True),
    sa.Column('document_status', sa.Enum('unverified', 'pending_review', 'verified', 'rejected', name='documentstatus'), nullable=False),
    sa.Column('document_review_notes', sa.String(), nullable=True),
    sa.Column('document_reviewed_by_user_id', sa.String(), nullable=True),
    sa.Column('document_reviewed_at', sa.DateTime(), nullable=True),
    sa.Column('cooperative_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['cooperative_id'], ['cooperative_profiles.id'], ),
    sa.ForeignKeyConstraint(['document_reviewed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['home_harbour_id'], ['harbours.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('products',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('vendor_id', sa.String(), nullable=False),
    sa.Column('category_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('spec_summary', sa.Text(), nullable=True),
    sa.Column('port_location', sa.String(), nullable=True),
    sa.Column('price_hint', sa.Float(), nullable=True),
    sa.Column('in_stock', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['product_categories.id'], ),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendor_profiles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('catch_logs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('fisherman_id', sa.String(), nullable=False),
    sa.Column('species', sa.String(), nullable=False),
    sa.Column('quantity_kg', sa.Float(), nullable=False),
    sa.Column('catch_latitude', sa.Float(), nullable=True),
    sa.Column('catch_longitude', sa.Float(), nullable=True),
    sa.Column('harbour_id', sa.String(), nullable=True),
    sa.Column('device_recorded_at', sa.DateTime(), nullable=False),
    sa.Column('synced_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['fisherman_id'], ['fisherman_profiles.id'], ),
    sa.ForeignKeyConstraint(['harbour_id'], ['harbours.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rfqs',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('product_id', sa.String(), nullable=False),
    sa.Column('requested_by_user_id', sa.String(), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('open', 'responded', 'closed', name='rfqstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['requested_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rfqs')
    op.drop_table('catch_logs')
    op.drop_table('products')
    op.drop_table('fisherman_profiles')
    op.drop_table('vendor_profiles')
    with op.batch_alter_table('price_records', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_price_records_species'))
        batch_op.drop_index(batch_op.f('ix_price_records_record_date'))

    op.drop_table('price_records')
    op.drop_table('cooperative_profiles')
    op.drop_table('buyer_profiles')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_phone_number'))

    op.drop_table('users')
    op.drop_table('product_categories')
    op.drop_table('pfz_advisories')
    op.drop_table('harbours')
    # ### end Alembic commands ###
